packages:
  - 'apps/*'

allowBuilds:
  '@biomejs/biome': true
  core-js: false
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@rtorcato/repo-tooling'
  - '@types/node@25.9.3'
  - '@rtorcato/shared-docs@1.12.0'
  - '@rtorcato/repo-ai@3.1.2'
overrides:
  fast-uri: '^3.1.6'
  js-yaml: '^4.3.1'
