packages:
  - 'apps/*'

allowBuilds:
  '@biomejs/biome': true
  core-js: false
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@rtorcato/js-tooling@2.8.0'
  - '@rtorcato/js-tooling@2.9.0'
