import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/contract', 'guides/browser-support'],
		},
		{
			type: 'category',
			label: 'API Reference',
			items: [
				{
					type: 'autogenerated',
					dirName: 'api',
				},
			],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
