import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/contract', 'guides/browser-support'],
		},
		{
			type: 'category',
			label: 'Modules',
			// Hand-written per-module guides (examples + MDN/caniuse links) live in docs/modules.
			items: [{ type: 'autogenerated', dirName: 'modules' }],
		},
		{
			type: 'category',
			label: 'API Reference',
			// TypeDoc emits one page per module into docs/api; Docusaurus scans them.
			link: { type: 'doc', id: 'api/index' },
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
