import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// The API Reference items are generated by docusaurus-plugin-typedoc
// (sidebar.autoConfiguration) into docs/api/typedoc-sidebar.cjs. That file is
// gitignored and regenerated on every build; it exists by the time Docusaurus
// loads sidebars because the typedoc plugin runs first. Fall back to an
// autogenerated scan if it is somehow missing (e.g. a partial build).
let apiItems: SidebarsConfig['docs']
try {
	apiItems = require('./docs/api/typedoc-sidebar.cjs')
} catch {
	apiItems = [{ type: 'autogenerated', dirName: 'api' }]
}

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/contract', 'guides/browser-support'],
		},
		{
			type: 'category',
			label: 'API Reference',
			items: Array.isArray(apiItems) ? apiItems : [apiItems],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
